pipeline {
    agent { label 'linux' }
    
    tools {
        maven 'Maven 3.x'
        jdk 'Java 11'
    }

    environment {
        AIKIDO_API_KEY = credentials('aikido-token')
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Security Scan (Aikido)') {
            steps {
                sh '''
                  aikido-api-client scan-release simple-java-maven-app $GIT_COMMIT \
                    --apikey $AIKIDO_API_KEY \
                    --fail-on-sast-scan \
                    --fail-on-secrets-scan
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
